trigger:
- '*'
pool:
  name: 'MyAgentPool'

steps:

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'helloworldsnykconnection'
    testType: 'container'
    dockerImageName: 'helloworlddotnetwebapp:178'
    dockerfilePath: 'devopswebappcontreg.azurecr.io'
    monitorWhen: 'always'
    failOnIssues: true