apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: helloworld-vpa
spec:
  TargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hwapp-replicaset
  updatePolicy:
    updateMode: "Auto"
